version: "3.8"
services:
  ltp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/config/local.yaml
    volumes:
      - ./config:/config:ro
  redis:
    image: redis:7
    ports:
      - "6379:6379"
