services:
  ltp-service:
    build: .
    container_name: ltp-service
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SERVER_PORT: 8080

      USE_REDIS: "true"
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      REDIS_TTL: "60s"

      CONFIG_PATH: "/tmp/local.yaml"

    volumes:
      - ./config/local.yaml:/tmp/local.yaml:ro

  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ltp-tests
    depends_on:
      - ltp-service
      - redis
    command: >
      sh -c "sleep 5 &&
             go test ./internal/integrationtest/... -tags=integration -v"
    volumes:
      - .:/app

volumes:
  redis_data:
